services:
  - type: web
    name: student-tracker-backend
    env: python
    buildCommand: pip install -r requirements.txt gunicorn
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: root
      - key: DB_NAME
        value: student_academic_tracker
